/* Telemetrio MCP landing page behaviour. Runtime settings come from #mcp-config (generated by build.py). */
(() => {
  const cfg = JSON.parse(document.getElementById('mcp-config').textContent);
  const root = document.documentElement;
  const params = new URLSearchParams(location.search);
  const reduceMotion = matchMedia('(prefers-reduced-motion: reduce)').matches;
  const live = document.getElementById('live');
  const variant = root.dataset.variant || cfg.experiment.default;

  // ---------- Analytics ----------
  // Events go to the data layer only. Never include freeform prompt or search text.
  const dataLayer = (window[cfg.analytics.dataLayer] = window[cfg.analytics.dataLayer] || []);
  const debug = params.get('debug') === 'analytics';
  const track = (event, data = {}) => {
    const payload = { event, page_variant: cfg.pageVariant, experiment_variant: variant, ...data };
    dataLayer.push(payload);
    if (debug) console.info('[analytics]', payload);
  };
  window.telemetrioMcp = { track };
  track('mcp_landing_view');

  const announce = (msg) => { live.textContent = ''; setTimeout(() => { live.textContent = msg; }, 30); };
  const storage = {
    get(key) { try { return JSON.parse(sessionStorage.getItem(key)); } catch (e) { return null; } },
    set(key, value) { try { sessionStorage.setItem(key, JSON.stringify(value)); } catch (e) { /* storage unavailable */ } },
  };

  // ---------- Mobile menu ----------
  const header = document.querySelector('.site-header');
  const menuBtn = document.querySelector('.menu-btn');
  const setMenu = (open) => {
    header.classList.toggle('menu-open', open);
    menuBtn.setAttribute('aria-expanded', String(open));
    menuBtn.querySelector('.sr-only').textContent = open ? cfg.strings.menuClose : cfg.strings.menuOpen;
  };
  menuBtn.addEventListener('click', () => setMenu(!header.classList.contains('menu-open')));
  header.querySelectorAll('.header-nav a').forEach((a) => a.addEventListener('click', () => setMenu(false)));
  document.addEventListener('keydown', (e) => {
    if (e.key === 'Escape' && header.classList.contains('menu-open')) { setMenu(false); menuBtn.focus(); }
  });

  // ---------- Demo scenarios (prepared content, no live search) ----------
  const tabs = [...document.querySelectorAll('.demo-tab')];
  let currentScenario = tabs.length ? tabs[0].dataset.scenario : null;
  const selectTab = (tab, { focus = false, user = false } = {}) => {
    tabs.forEach((t) => {
      const on = t === tab;
      t.setAttribute('aria-selected', String(on));
      t.tabIndex = on ? 0 : -1;
      document.getElementById(t.getAttribute('aria-controls')).hidden = !on;
    });
    currentScenario = tab.dataset.scenario;
    document.querySelectorAll('.demo-cta [data-assistant]').forEach((a) => { a.dataset.scenario = currentScenario; });
    if (focus) tab.focus();
    if (user) track('mcp_demo_select', { scenario_id: currentScenario });
  };
  // "See an example" lands keyboard users on the scenario selector.
  document.querySelectorAll('a[href="#demo"]').forEach((a) => a.addEventListener('click', () => {
    const selected = tabs.find((t) => t.getAttribute('aria-selected') === 'true');
    if (selected) setTimeout(() => selected.focus({ preventScroll: true }), 0);
  }));
  tabs.forEach((tab, i) => {
    tab.addEventListener('click', () => selectTab(tab, { user: true }));
    tab.addEventListener('keydown', (e) => {
      const move = { ArrowRight: 1, ArrowLeft: -1, Home: -i, End: tabs.length - 1 - i }[e.key];
      if (move === undefined) return;
      e.preventDefault();
      selectTab(tabs[(i + move + tabs.length) % tabs.length], { focus: true, user: true });
    });
  });

  // ---------- Copy prompt ----------
  const selectText = (el) => {
    const range = document.createRange();
    range.selectNodeContents(el);
    const sel = getSelection();
    sel.removeAllRanges();
    sel.addRange(range);
  };
  const copyText = async (text, el) => {
    try {
      if (navigator.clipboard && window.isSecureContext) { await navigator.clipboard.writeText(text); return true; }
    } catch (e) { /* fall through */ }
    try {
      selectText(el);
      const ok = document.execCommand('copy');
      if (ok) getSelection().removeAllRanges();
      return ok;
    } catch (e) { return false; }
  };
  document.addEventListener('click', async (e) => {
    const btn = e.target.closest('.copy-btn');
    if (!btn) return;
    const target = document.getElementById(btn.dataset.copy);
    const label = btn.querySelector('.copy-label');
    const ok = await copyText(target.textContent.trim(), target);
    const errorId = btn.dataset.copy + '-error';
    document.getElementById(errorId)?.remove();
    if (ok) {
      btn.dataset.state = 'copied';
      label.textContent = btn.dataset.copiedLabel || cfg.strings.copied;
      announce(btn.dataset.copiedLabel || cfg.strings.copied);
      clearTimeout(btn._t);
      btn._t = setTimeout(() => { delete btn.dataset.state; label.textContent = btn.dataset.label; }, 2000);
      if (btn.dataset.promptId) track('mcp_prompt_copy', { prompt_id: btn.dataset.promptId, cta_location: btn.dataset.location });
    } else {
      selectText(target);
      const msg = document.createElement('p');
      msg.className = 'copy-error';
      msg.id = errorId;
      msg.textContent = cfg.strings.copyFailed;
      btn.insertAdjacentElement('afterend', msg);
      announce(cfg.strings.copyFailed);
    }
  });

  // ---------- Connection setup ----------
  const setupSeen = new Set();
  const setupView = (assistant, trigger) => {
    if (setupSeen.has(assistant)) return;
    setupSeen.add(assistant);
    track('mcp_setup_view', { assistant, trigger });
  };
  // Carry the selected example (or a prompt composed on the page) into that assistant's setup card.
  const setFirstPrompt = (assistant, text, promptId) => {
    const el = document.getElementById(`setup-${assistant}-prompt`);
    if (!text || !el) return;
    el.textContent = text;
    const btn = document.querySelector(`[data-copy="setup-${assistant}-prompt"]`);
    if (btn && promptId) btn.dataset.promptId = promptId;
  };
  const openSetup = (assistant, prompt) => {
    const card = document.getElementById(`setup-${assistant}`);
    if (!card) return;
    if (prompt) { setFirstPrompt(assistant, prompt.text, prompt.id); storage.set('mcp_selected_prompt', { assistant, ...prompt }); }
    card.scrollIntoView({ behavior: reduceMotion ? 'auto' : 'smooth', block: 'start' });
    card.querySelector('h3').focus({ preventScroll: true });
    card.classList.add('is-targeted');
    setTimeout(() => card.classList.remove('is-targeted'), 1800);
    history.replaceState(null, '', `#setup-${assistant}`);
    setupView(assistant, 'cta');
  };
  document.addEventListener('click', (e) => {
    const link = e.target.closest('a[data-assistant]');
    if (!link) return;
    const { assistant, location: ctaLocation, scenario, promptFrom } = link.dataset;
    const source = promptFrom && document.getElementById(promptFrom);
    const prompt = source ? { text: source.textContent.trim(), id: source.dataset.promptId }
      : scenario && cfg.scenarios[scenario] ? { text: cfg.scenarios[scenario], id: `scenario:${scenario}` } : null;
    track('mcp_connect_click', { assistant, cta_location: ctaLocation, scenario_id: (prompt && prompt.id) || null });
    if (link.getAttribute('href').startsWith('#setup-')) { e.preventDefault(); openSetup(assistant, prompt); }
  });
  const saved = storage.get('mcp_selected_prompt');
  if (saved) setFirstPrompt(saved.assistant, saved.text, saved.id);
  if (/^#setup-(claude|chatgpt)$/.test(location.hash)) openSetup(location.hash.slice(7));
  if ('IntersectionObserver' in window) {
    const io = new IntersectionObserver((entries) => entries.forEach((en) => {
      if (en.isIntersecting) { setupView(en.target.dataset.assistant, 'scroll'); io.unobserve(en.target); }
    }), { threshold: 0.5 });
    document.querySelectorAll('.setup-card').forEach((c) => io.observe(c));
  }

  // ---------- Confirmed connection status ----------
  // Only a backend confirmation counts as a connection. Outbound clicks are never treated as installs.
  // Proposed response shape: { "claude": { "connected": true, "firstSearch": false, "error": null }, "chatgpt": { ... } }
  if (cfg.statusEndpoint) {
    fetch(cfg.statusEndpoint, { credentials: 'include' })
      .then((r) => (r.ok ? r.json() : null))
      .then((status) => {
        if (!status) return;
        Object.entries(status).forEach(([assistant, s]) => {
          const msg = document.querySelector(`#setup-${assistant} .status-msg`);
          if (s && s.connected && msg) {
            msg.textContent = cfg.strings.connected;
            msg.classList.add('is-connected');
            track('mcp_connection_success', { assistant });
          }
          if (s && s.firstSearch) track('mcp_first_search_success', { assistant });
          if (s && s.error) track('mcp_connection_error', { assistant, error_category: s.error });
        });
      })
      .catch(() => { /* status unavailable: keep the default instructions */ });
  }
})();
